package:
    name: repeatmodeler
    version: 1.0.11
source:
    md5: c148b4b56bb3fbd4e9ba88ac8736baa3
    url: http://www.repeatmasker.org/RepeatModeler/RepeatModeler-open-1.0.11.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    build:
        - blast 2.2.31 1
        - boost 1.57.0 4
        - bzip2 1.0.6 1
        - icu 58.2 0
        - libgcc 7.2.0 h69d50b8_2
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h14c3975_0
        - rmblast 2.2.28 3
        - zlib 1.2.11 h470a237_3
    run:
        - perl >=5.26.2,<5.27.0a0
        - perl-text-soundex
        - recon
        - repeatmasker
        - repeatscout
        - rmblast
        - trf
test:
    commands:
        - RepeatModeler > /dev/null
about:
    home: http://www.repeatmasker.org/RepeatModeler.html
    license: Open Software License v2.1
    summary: RepeatModeler is a de-novo repeat family identification and modeling
        package.
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:RepeatModeler
